# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - LoveDuckie\Silverstripe\Robots\Extensions\SiteConfigExtension

